### ISSUE TITLE
failed to load autoload.php

### ISSUE THREAD

**Issue by superluffa-kei** [irimiaionut/wordpress-plugin-firebase-cloud-messaging-integration#1]
Hi,

Thank you for the interesting plugin. When trying to load the plugin, I've got an error message saying, 

Warning: require_once(/var/www/html/wp-content/plugins//FCM-integration/vendor/autoload.php): failed to open stream: No such file or directory in /var/www/html/wp-content/plugins/FCM-integration/FCMNotificationManager.php on line 3 Fatal error: require_once(): Failed opening required '/var/www/html/wp-content/plugins//FCM-integration/vendor/autoload.php' (include_path='.:/usr/local/lib/php') in /var/www/html/wp-content/plugins/FCM-integration/FCMNotificationManager.php on line 3

It seems that there is no such "autoload.php".

**Comment by irimiaionut** [comment]
Hello superluffa, just run composer install in root project. This will install all project dependencies

**Comment by superluffa-kei** [comment]
Thank you. This resolves the problem.
