### ISSUE TITLE
How to send a manual notification?

### ISSUE THREAD

**Issue by superluffa-kei** [irimiaionut/wordpress-plugin-firebase-cloud-messaging-integration#2]
Hi, 

The plugin works—thank you!
However, I'd like to send the push notification manually. When searching for clues by looking at the source lines, I could see that it actually has that feature. The problem is, I cannot find the relevant button in the Wordpress admin, publish, etc page. (The only thing I can see is the push notification column.) Any hint?

**Comment by superluffa-kei** [comment]
Oh, for some reasons. Now I see the "Push Notification" in the list. Problem resolved :)

**Comment by irimiaionut** [comment]
The post needs to be included in the categories specified in plugin configuration page, most probably this was the issue. Have fun
